name: Unzip ProjetOrange.zip

on:
  push:
    branches:
      - main
    paths:
      - "ProjetOrange.zip"  # Déclenche le workflow quand le ZIP est pushé

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip ProjetOrange.zip
        run: |
          unzip ProjetOrange.zip -d ProjetOrange
          rm ProjetOrange.zip  # Supprime le zip après extraction

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Unzipped ProjetOrange.zip"
          git push
